# Parche de compatibilidad para packs de armadura 3D (CEM)
# Requiere el mod "Armor CEM Compat".
# NO modifica el pack de armadura: se carga ENCIMA y solo anade archivos.
#
# variante 1 = el modelo 3D del pack original (intacto)
# variante 2 = player_helmet2.jem -> geometria vanilla
# Regla: si la pieza NO es vanilla, usar la variante 2 (el "!" niega el patron).
models.1=2
armor_item.1=!head:minecraft:*_helmet
