# Just 3D Armors HMI - compat con armaduras de mods
# Requiere el mod "Armor CEM Compat", que aporta la propiedad armor_item.
# variante 1 = zombie_leggings.jem   -> geometria vanilla (cualquier armadura de mod)
# variante 2 = zombie_leggings2.jem  -> el modelo 3D original de nagi, intacto
models.1=2
armor_item.1=legs:minecraft:*_leggings
